### ISSUE TITLE
关于开源协议

### ISSUE THREAD

**Issue by solos** [moneyinto/canvas-ppt#2]
你好 感觉这个项目很酷 想问下这个项目开源协议是什么 是否可以用于商业项目 谢谢

**Comment by moneyinto** [comment]
你那边是打算商用吗，整体的基础功能已经有了，自我感觉还没有达到商用的标准，需要继续维护，最近这段时间工作比较繁忙，没继续优化
商用的话，代码肯定自己需要进一步优化
我自己这边也希望能得到一下反馈来完善开源项目
可否进一步沟通 微信 15962456954

solos ***@***.***> 于2023年9月13日周三 14:26写道：

**Comment by solos** [comment]
大佬你好，我们想用angular搞一个在线幻灯片的应用，想基于你的代码开发，我们可以出一笔费用，谢谢。
